#version: "1.0"
services:
  spark-worker-3:
    image: raulcsouza/spark-worker-hadoop
    container_name: spark-worker-3
    hostname: spark-worker-3
    tty: true
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=10.0.1.14"
    networks:
      cluster-net:
        ipv4_address: 10.0.1.14
  spark-worker-4:
    image: raulcsouza/spark-worker-hadoop
    container_name: spark-worker-4
    hostname: spark-worker-4
    tty: true
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
    environment:
     - "SPARK_LOCAL_IP=10.0.1.15"
    networks:
      cluster-net:
        ipv4_address: 10.0.1.15
networks:
  cluster-net:
    driver: overlay
    external: true
