#version: "1.0"
services:
  spark-worker-1:
    image: raulcsouza/spark-worker-hadoop
    container_name: spark-worker-1
    hostname: spark-worker-1
    tty: true
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=10.0.1.12"
    networks:
      cluster-net:
        ipv4_address: 10.0.1.12
  spark-worker-2:
    image: raulcsouza/spark-worker-hadoop
    container_name: spark-worker-2
    hostname: spark-worker-2
    tty: true
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
    environment:
     - "SPARK_LOCAL_IP=10.0.1.13"
    networks:
      cluster-net:
        ipv4_address: 10.0.1.13
networks:
  cluster-net:
    driver: overlay
    external: true
